### ISSUE TITLE
Encoding Help

### ISSUE THREAD

**Issue by Budapresst** [wwwiiilll/pyxlsb#20]
Hi...
I'm having a problem with encoding and I'm not not too familiar with Python, so I'm hoping you have a second to help me out.

I'm using your xlsb to csv example verbatim on a workbook that has lots of foreign (Hungarian) characters.  When it hits the first special character, I get this error: UnicodeEncodeError: 'ascii' codec can't encode character u'\xc1' in position 1: ordinal not in range(128) 

I'm expecting that the c.v in this line: writer.writerow([c.v for c in row])  needs to be encode before writing it to the file, but I don't know how to implement the encoding.  I tried some stuff like c.v.encode('utf-8') but, of course, it didn't work.  Could you point me in the right direction?

Thanks!
-Alec

**Comment by wwwiiilll** [comment]
I assume you're using Python 2.x. This is happening because the built-in csv module doesn't really support unicode.

The best way to fix this would be to upgrade to Python 3, if that's possible for you.

Otherwise, make sure you open the file in `wb` mode and your `c.v.encode('utf-8')` should work I think.

**Comment by wwwiiilll** [comment]
I'll close this since it's not directly related to the project, but we can still use it for discussion.

**Comment by Budapresst** [comment]
Thank you for the help, Will!
